### ISSUE TITLE
`userscripts/align-attributes` fails when header contains attribute w/o value

### ISSUE THREAD

**Issue by nikolay-borzov** [Yash-Singh1/eslint-plugin-userscripts#39]
Script header:
```js
// ==UserScript==
// @name        My script
// @description Allows do things
// @namespace   myscript
// @version     1.0.0
// @author      john-doe
// @license     MIT
// @include     *
// @run-at      document-start
// @noframes
// @grant       GM_addStyle
// ==/UserScript==
```

ESLint: `8.14.0`

Stack trace:
```
TypeError: Error while loading rule 'userscripts/align-attributes': Cannot read properties of null (reading '1')
Occurred while linting ***\dist\my-script.user.js
    at Object.create (***\node_modules\eslint-plugin-userscripts\lib\rules\align-attributes.js:48:65)
    at createRuleListeners (***\node_modules\eslint\lib\linter\linter.js:922:21)
    at ***\node_modules\eslint\lib\linter\linter.js:1104:31
    at Array.forEach (<anonymous>)
    at runRules (***\node_modules\eslint\lib\linter\linter.js:1041:34)
    at Linter._verifyWithoutProcessors (***\node_modules\eslint\lib\linter\linter.js:1389:31)
    at Linter._verifyWithConfigArray (***\node_modules\eslint\lib\linter\linter.js:1729:21)
    at Linter.verify (***\node_modules\eslint\lib\linter\linter.js:1471:65)
    at Linter.verifyAndFix (***\node_modules\eslint\lib\linter\linter.js:1953:29)
    at verifyText (***\node_modules\eslint\lib\cli-engine\cli-engine.js:245:48)
```

The trace points at
```js
} else if (inMetadata && comment.value.trim().startsWith('@')) {
  metadata.push({
    key: comment.value.trim().slice(1).split(/\s/)[0],
    space: /^\S*(\s+)/.exec(comment.value.trim().slice(1))>>><<<[1].length,
    line: comment.loc.start.line,
    comment
  });
}
```

<details>
  <summary>`/^\S*(\s+)/.exec(comment.value.trim().slice(1))` log result</summary>

```
[
  'name        ',
  '        ',
  index: 0,
  input: 'name        My script',
  groups: undefined
]

[
  'description ',
  ' ',
  index: 0,
  input: 'description Allows do things',
  groups: undefined
]

[
  'namespace   ',
  '   ',
  index: 0,
  input: 'namespace   myscript',
  groups: undefined
]

[
  'version     ',
  '     ',
  index: 0,
  input: 'version     1.0.0',
  groups: undefined
]

[
  'author      ',
  '      ',
  index: 0,
  input: 'author      john-doe',
  groups: undefined
]

[
  'license     ',
  '     ',
  index: 0,
  input: 'license     MIT',
  groups: undefined
]

[
  'include     ',
  '     ',
  index: 0,
  input: 'include     *',
  groups: undefined
]

[
  'run-at      ',
  '      ',
  index: 0,
  input: 'run-at      document-start',
  groups: undefined
]

null
```
</details>

**Comment by Yash-Singh1** [comment]
Hey @nikolay-borzov, thanks for creating this issue! Would you like to create a PR?

**Comment by nikolay-borzov** [comment]
I'd like to.
I managed to fix the issue, but for some reason error is still triggered

<details>
<summary>Fix diff</summary>

```diff
diff --git a/lib/rules/align-attributes.js b/lib/rules/align-attributes.js  
index 1821000..be7bbd3 100644
--- a/lib/rules/align-attributes.js
+++ b/lib/rules/align-attributes.js
@@ -45,7 +45,7 @@ module.exports = {
       } else if (inMetadata && comment.value.trim().startsWith('@')) {     
         metadata.push({
           key: comment.value.trim().slice(1).split(/\s/)[0],
-          space: /^\S*(\s+)/.exec(comment.value.trim().slice(1))[1].length,
+          space: /^\S*(\s*)/.exec(comment.value.trim().slice(1))[1].length,
           line: comment.loc.start.line,
           comment
         });
@@ -83,8 +83,10 @@ module.exports = {
             // istanbul ignore else
             if (
               metadatapoint.key.length + metadatapoint.space !==
-              totalSpacing
+              totalSpacing && metadatapoint.space !== 0
             ) {
+              console.log(metadatapoint)
+
               const startColumn = /^(.*?@\S*)/.exec(
                 sourceCode.getLines()[metadatapoint.line - 1]
               )[1].length;
diff --git a/tests/lib/rules/align-attributes.js b/tests/lib/rules/align-attributes.js
index 96ec212..1c613ae 100644
--- a/tests/lib/rules/align-attributes.js
+++ b/tests/lib/rules/align-attributes.js
@@ -41,10 +41,12 @@ ruleTester.run('align-attributes', rule, {
       code: `// ==UserScript==
       // @name                  some name
       // @description hey there
+      // @nowrap
       `,
       output: `// ==UserScript==
       // @name            some name
       // @description     hey there
+      // @nowrap
       `,
       options: [5],
       errors: [
```
</details>

**Comment by Yash-Singh1** [comment]
At line 51, you need to change the value of the space key to be `0` when the key is of format `@keyname` without any value. Changing the `+` to a `*` won't capture that specific group because the whitespace still isn't present.

```diff
         metadata.push({
           key: comment.value.trim().slice(1).split(/\s/)[0],
-          space: /^\S*(\s+)/.exec(comment.value.trim().slice(1))[1].length,
+          space: /^\S*(\s*)/.exec(comment.value.trim().slice(1))[1].length,
           line: comment.loc.start.line,
           comment
         });
```
