### ISSUE TITLE
`userscripts/compat-grant` fails for `greasemonkey: '4.x'` and `@grant GM_getValue`

### ISSUE THREAD

**Issue by nikolay-borzov** [Yash-Singh1/eslint-plugin-userscripts#40]
Script header:
```
// ==UserScript==
// @name         My script
// @description  Allows do thins
// @namespace    myscript
// @version      1.0.0
// @author       john-dow
// @license      MIT
// @include      *
// @grant        GM_getValue
// ==/UserScript==
```

ESLint: `8.14.0`

ESLint config;
```
settings: {
  userscriptVersions: {
    tampermonkey: '4.x',
    greasemonkey: '4.x',
  },
},

rules: {
  'userscripts/compat-grant': ['error', { requireAllCompatible: true }],
  'userscripts/compat-headers': ['error', { requireAllCompatible: true }],
}
```

Stack trace:
```
TypeError: Error while loading rule 'userscripts/compat-grant': Invalid comparator: >=0.3-beta
Occurred while linting <text>
    at Comparator.parse (***\node_modules\eslint-plugin-userscripts\node_modules\semver\classes\comparator.js:38:13)
    at new Comparator (***\node_modules\eslint-plugin-userscripts\node_modules\semver\classes\comparator.js:22:10)
    at ***\node_modules\eslint-plugin-userscripts\node_modules\semver\classes\range.js:133:47
    at Array.map (<anonymous>)
    at Range.parseRange (***\node_modules\eslint-plugin-userscripts\node_modules\semver\classes\range.js:133:35)
    at ***\node_modules\eslint-plugin-userscripts\node_modules\semver\classes\range.js:34:22
    at Array.map (<anonymous>)
    at new Range (***\node_modules\eslint-plugin-userscripts\node_modules\semver\classes\range.js:34:8)
    at intersects (***\node_modules\eslint-plugin-userscripts\node_modules\semver\ranges\intersects.js:4:8)
    at validator (***\node_modules\eslint-plugin-userscripts\lib\rules\compat-grant.js:26:15)
    at Object.create (***\node_modules\eslint-plugin-userscripts\lib\utils\createValidator.js:208:17)
    at createRuleListeners (***\node_modules\eslint\lib\linter\linter.js:922:21)
    at ***\node_modules\eslint\lib\linter\linter.js:1104:31
    at Array.forEach (<anonymous>)
    at runRules (***\node_modules\eslint\lib\linter\linter.js:1041:34)
    at Linter._verifyWithoutProcessors (***\node_modules\eslint\lib\linter\linter.js:1389:31)
    at Linter._verifyWithConfigArray (**\node_modules\eslint\lib\linter\linter.js:1729:21)
    at Linter.verify (***\node_modules\eslint\lib\linter\linter.js:1471:65)
    at Linter.verifyAndFix (***\node_modules\eslint\lib\linter\linter.js:1953:29)
    at verifyText (***\node_modules\eslint\lib\cli-engine\cli-engine.js:245:48)
    at CLIEngine.executeOnText (***\node_modules\eslint\lib\cli-engine\cli-engine.js:919:26)
    at ESLint.lintText (***\node_modules\eslint\lib\eslint\eslint.js:592:23)
    at RollupPluginESLintBundle.lint (***\build\rollup-plugin-eslint-bundle\dist\index.cjs:102:39)
    at Object.renderChunk (***\build\rollup-plugin-eslint-bundle\dist\index.cjs:149:21)
    at ***\node_modules\rollup\dist\shared\rollup.js:22834:37 {
```

**Comment by Yash-Singh1** [comment]
Hey @nikolay-borzov, thanks for creating this issue! It turns out it was caused due to the fact that `semver` was doing strict validation on the ranges in the data. I just pushed a fix with 9529130c360ea4e09f81b235477f7c9d8faecee1.
